services:
  - type: web
    name: pnap-mis
    runtime: docker
    rootDir: pnap-mis
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 12h
      - key: CORS_ORIGIN
        value: "*"
      - key: CLIENT_ORIGIN
        value: "*"
      - key: UPLOAD_DIR
        value: uploads
      - key: MAX_UPLOAD_MB
        value: "5"
