const fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {monitorEventLoopDelay}=require('node:perf_hooks');const {start}=require('./harness.cjs');
const {EJSON}=require('node:module').createRequire(path.resolve(__dirname,'../../../pnap-mis/server/package.json'))('bson');
const out=path.join(__dirname,`level-${(process.env.O7_LEVEL||'').toLowerCase()}.json`);
const q='?days=365&from=2025-09-09T13:09:03.542Z',urls={summary:'/api/dashboard/summary'+q,scope:'/api/dashboard/scope'+q,org:'/api/dashboard/org-breakdown'+q,membership:'/api/dashboard/membership'+q,campaigns:'/api/dashboard/campaigns'+q,meetings:'/api/dashboard/meetings'+q+'&yearBasis=CALENDAR&years=5',reports:'/api/dashboard/reports'+q,inactiveUnits:'/api/dashboard/inactive-units'+q+'&level=BASIC_UNIT&page=1&limit=10',inactiveMembers:'/api/dashboard/inactive-members'+q+'&page=1&limit=10'};
const pct=(a,p)=>{const s=[...a].sort((x,y)=>x-y),i=(s.length-1)*p;return s[Math.floor(i)]+(s[Math.ceil(i)]-s[Math.floor(i)])*(i%1)};
const stats=a=>({n:a.length,mean:a.reduce((x,y)=>x+y,0)/a.length,p50:pct(a,.5),p90:pct(a,.9),p95:pct(a,.95),p99:pct(a,.99),max:Math.max(...a)});
function ticks(){return os.cpus().reduce((a,c)=>{for(const[k,v]of Object.entries(c.times)){a.t+=v;if(k==='idle')a.i+=v}return a},{t:0,i:0})}
async function measure(h,fn){h.analytics.invalidateCache();h.resetLog();const eld=monitorEventLoopDelay({resolution:1});eld.enable();const cpu=process.cpuUsage(),host=ticks(),rss0=process.memoryUsage().rss,t=performance.now();const responses=await fn();const wallMs=performance.now()-t,p=process.cpuUsage(cpu),host1=ticks();eld.disable();const commands=h.getLog().flatMap(x=>x.commands);return{wallMs,statuses:responses.map(x=>x.status),bytes:responses.reduce((a,x)=>a+x.bytes,0),hashes:responses.map(x=>x.hash),dbOperations:commands.length,roleAggregations:commands.filter(x=>x.collection==='roleassignments'&&x.type==='aggregate').length,nodeCpuPct:(p.user+p.system)/1000/wallMs*100,hostCpuPct:((host1.t-host.t)-(host1.i-host.i))/(host1.t-host.t)*100,eventLoopP95Ms:Number(eld.percentile(95))/1e6,eventLoopMaxMs:Number(eld.max)/1e6,rssStart:rss0,rssEnd:process.memoryUsage().rss,freeRam:os.freemem(),commands}};
const summarize=rows=>({completionMs:stats(rows.map(x=>x.wallMs)),responseBytes:stats(rows.map(x=>x.bytes)),dbOperations:stats(rows.map(x=>x.dbOperations)),roleAggregations:stats(rows.map(x=>x.roleAggregations)),nodeCpuPct:stats(rows.map(x=>x.nodeCpuPct)),hostCpuPct:stats(rows.map(x=>x.hostCpuPct)),eventLoopP95Ms:stats(rows.map(x=>x.eventLoopP95Ms)),rssEnd:stats(rows.map(x=>x.rssEnd)),freeRam:stats(rows.map(x=>x.freeRam)),allHttp200:rows.every(x=>x.statuses.every(s=>s===200))});
function planStages(x,out=[]){if(!x||typeof x!=='object')return out;if(typeof x.stage==='string')out.push(x.stage);for(const v of Object.values(x))planStages(v,out);return out}
async function integrity(db){const cols=['provinces','districts','areas','basicunits','members','roleassignments','users'],counts=Object.fromEntries(await Promise.all(cols.map(async c=>[c,await db.collection(c).countDocuments()])));const orphanMembers=await db.collection('members').countDocuments({basicUnitId:{$nin:await db.collection('basicunits').distinct('_id')}}),orphanRoles=await db.collection('roleassignments').countDocuments({$or:[{memberId:{$nin:await db.collection('members').distinct('_id')}},{unitId:{$nin:[...(await db.collection('provinces').distinct('_id')),...(await db.collection('districts').distinct('_id')),...(await db.collection('areas').distinct('_id')),...(await db.collection('basicunits').distinct('_id'))]}}]}),duplicateCnic=await db.collection('members').aggregate([{$group:{_id:'$cnic',n:{$sum:1}}},{$match:{n:{$gt:1}}},{$count:'n'}]).toArray();return{counts,orphanMembers,orphanRoles,duplicateCnicGroups:duplicateCnic[0]?.n||0,passed:orphanMembers===0&&orphanRoles===0&&!(duplicateCnic[0]?.n)}}
(async()=>{const h=await start();try{
 const environment=await h.environment(),integrityResult=await integrity(h.db);
 const cold=[];for(let i=0;i<30;i++)cold.push(await measure(h,()=>Promise.all([h.request(urls.inactiveUnits,{cold:false})])));
 const firstRole=[...new Map(cold[0].commands.filter(x=>x.collection==='roleassignments'&&x.type==='aggregate').map(x=>[x.signature,x])).values()];const rolePipelineExplains=[];
 for(const c of firstRole){const cmd=EJSON.deserialize(c.command),exp=await h.db.command({explain:{aggregate:'roleassignments',pipeline:cmd.pipeline,cursor:{}},verbosity:'executionStats'}),stages=planStages(exp);rolePipelineExplains.push({signature:c.signature,stages:[...new Set(stages)],hasCollscan:stages.includes('COLLSCAN'),hasSort:stages.includes('SORT'),executionStats:exp.stages?.[0]?.$cursor?.executionStats||exp.executionStats||null})}
 const group3=[];for(let i=0;i<12;i++)group3.push(await measure(h,()=>Promise.all([urls.summary,urls.org,urls.inactiveUnits].map(u=>h.request(u,{cold:false})))));
 const staged=[];for(let i=0;i<10;i++)staged.push(await measure(h,async()=>{const a=await Promise.all([urls.summary,urls.scope,urls.org].map(u=>h.request(u,{cold:false})));const b=await Promise.all([urls.membership,urls.campaigns,urls.meetings,urls.reports,urls.inactiveUnits,urls.inactiveMembers].map(u=>h.request(u,{cold:false})));return[...a,...b]}));
 const concurrency={};for(const n of [1,3,5,10]){const rows=[];for(let i=0;i<3;i++)rows.push(await measure(h,()=>Promise.all(Array.from({length:n},()=>h.request(urls.inactiveUnits,{cold:false})))));concurrency[n]={...summarize(rows),rows:rows.map(({commands,...r})=>r)}}
 const result={level:process.env.O7_LEVEL,database:h.dbName,environment,integrity:integrityResult,coldSnapshot:{...summarize(cold),rows:cold.map(({commands,...r})=>r)},rolePipelineExplains,group3:{...summarize(group3),singleflightVerified:group3.every(x=>x.roleAggregations===4),rows:group3.map(({commands,...r})=>r)},stagedDashboard:{...summarize(staged),rows:staged.map(({commands,...r})=>r)},moderateConcurrency:concurrency};fs.writeFileSync(out,JSON.stringify(result,null,2));console.log(JSON.stringify({level:result.level,cold:result.coldSnapshot.completionMs,group3:result.group3.completionMs,staged:result.stagedDashboard.completionMs},null,2));
 }finally{await h.close()}})().catch(e=>{console.error(e.stack);process.exit(1)});
