const fs = require('node:fs'), path = require('node:path'), os = require('node:os');
const { monitorEventLoopDelay, performance } = require('node:perf_hooks');
const { start, root } = require('../o2/harness.cjs');
const cfg = require('../o2/benchmark-config.json');
const urls = Object.fromEntries(cfg.ops.map((x) => [x.name, x.url]));
const out = path.join(root, 'performance-tests/results/optimization/o6');
const stats = (a) => { const s = [...a].sort((x,y)=>x-y), q=(p)=>{const i=(s.length-1)*p;return s[Math.floor(i)]+(s[Math.ceil(i)]-s[Math.floor(i)])*(i%1)}; return {n:a.length,mean:a.reduce((x,y)=>x+y,0)/a.length,p50:q(.5),p90:q(.9),p95:q(.95),p99:q(.99),max:Math.max(...a)}; };
const ticks=()=>os.cpus().reduce((a,c)=>{for(const[k,v]of Object.entries(c.times)){a.t+=v;if(k==='idle')a.i+=v}return a},{t:0,i:0});
async function run(h,names,staged=false){h.analytics.invalidateCache();h.resetLog();const eld=monitorEventLoopDelay({resolution:1});eld.enable();const p0=process.cpuUsage(),s0=ticks(),t=performance.now();let rs;if(staged){const a=await Promise.all(['summary','scope','org-breakdown'].map(n=>h.request(urls[n],{cold:false})));const b=await Promise.all(['membership','campaigns','meetings','reports','inactive-units','inactive-members'].map(n=>h.request(urls[n],{cold:false})));rs=[...a,...b];}else rs=await Promise.all(names.map(n=>h.request(urls[n],{cold:false})));const wall=performance.now()-t,p=process.cpuUsage(p0),s1=ticks();eld.disable();const commands=h.getLog().flatMap(x=>x.commands);return{wall,statuses:rs.map(x=>x.status),hashes:rs.map(x=>x.hash),shapes:rs.map(x=>x.shapeHash),bytes:rs.reduce((a,x)=>a+x.bytes,0),dbOperations:commands.length,roleAggregations:commands.filter(x=>x.type==='aggregate'&&x.collection==='roleassignments').length,commands,processCpuPct:(p.user+p.system)/1000/wall*100,hostCpuPct:((s1.t-s0.t)-(s1.i-s0.i))/(s1.t-s0.t)*100,eventLoopP95Ms:Number(eld.percentile(95))/1e6};}
const summarize=r=>({latencyMs:stats(r.map(x=>x.wall)),responseBytes:stats(r.map(x=>x.bytes)),dbOperations:stats(r.map(x=>x.dbOperations)),roleAggregations:stats(r.map(x=>x.roleAggregations)),processCpuPct:stats(r.map(x=>x.processCpuPct)),hostCpuPct:stats(r.map(x=>x.hostCpuPct)),eventLoopP95Ms:stats(r.map(x=>x.eventLoopP95Ms)),errorRate:r.flatMap(x=>x.statuses).filter(x=>x>=400).length/r.flatMap(x=>x.statuses).length});
(async()=>{fs.mkdirSync(out,{recursive:true});const h=await start();try{const snapshot=[],group3=[],dashboard=[];for(let i=0;i<30;i++)snapshot.push(await run(h,['inactive-units']));for(let i=0;i<30;i++)group3.push(await run(h,['summary','org-breakdown','inactive-units']));for(let i=0;i<15;i++)dashboard.push(await run(h,[],true));const finalRun=process.env.O6_FINAL==='1',result={label:finalRun?'O6 FINAL RETAINED STATE':'O6 LOCAL PRE-OPTIMIZATION BASELINE',environment:await h.environment(),snapshot:summarize(snapshot),group3:summarize(group3),dashboard:summarize(dashboard),raw:{snapshot,group3,dashboard}};fs.writeFileSync(path.join(out,finalRun?'final.json':'baseline.json'),JSON.stringify(result,null,2));}finally{await h.close();}})().catch(e=>{console.error(e.stack);process.exit(1)});
